# Site settings
title:       __Innit__
email:       thelamacmdr@gmail.com
author:      Anthony Lam
description: ""
baseurl:     ""
url:         "https://anthonylam.github.io"

# Google analytics
google_analytics: UA-54297033-2

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: thelamacmdr

# Social icons
show_social_icons: false
github_username: AnthonyLam
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
